on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.17]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Set up staticcheck
        run: |
          wget -O staticcheck.tar.gz "https://github.com/dominikh/go-tools/releases/download/2021.1.1/staticcheck_linux_amd64.tar.gz"
          tar xvzf staticcheck.tar.gz && mv staticcheck staticcheck-bin
          mv staticcheck-bin/staticcheck .


      - name: staticcheck
        run: ./staticcheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
