on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.17]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Testing
        run: go test ./...
